-- Create Users Table
CREATE TABLE users
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username               VARCHAR(50)                             NOT NULL,
    password               VARCHAR(255)                            NOT NULL,
    email                  VARCHAR(255)                            NOT NULL,
    full_name              VARCHAR(255)                            NOT NULL,
    role                   VARCHAR(50)                             NOT NULL,
    facility_id            VARCHAR(50),
    district_id            VARCHAR(50),
    national_id            VARCHAR(50),
    active                 BOOLEAN                                 NOT NULL,
    locked                 BOOLEAN                                 NOT NULL,
    failed_login_attempts  INTEGER                                 NOT NULL,
    created_at             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by             BIGINT,
    deleted                BOOLEAN                                 NOT NULL,
    deleted_at             TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- Create Patients Table
CREATE TABLE patients
(
    id            UUID                        NOT NULL,
    full_name     VARCHAR(255)                NOT NULL,
    date_of_birth date                        NOT NULL,
    gender        VARCHAR(10)                 NOT NULL,
    guardian_name VARCHAR(255),
    phone_number  VARCHAR(20),
    address       TEXT,
    facility_id   VARCHAR(50)                 NOT NULL,
    deleted       BOOLEAN                     NOT NULL,
    deleted_at    TIMESTAMP WITHOUT TIME ZONE,
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by    BIGINT,
    CONSTRAINT pk_patients PRIMARY KEY (id)
);

-- Create Vaccine Batches Table
CREATE TABLE vaccine_batches
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    batch_number       VARCHAR(50)                             NOT NULL,
    vaccine_name       VARCHAR(100)                            NOT NULL,
    manufacturer       VARCHAR(100)                            NOT NULL,
    quantity_received  INTEGER                                 NOT NULL,
    quantity_remaining INTEGER                                 NOT NULL,
    expiry_date        date                                    NOT NULL,
    receipt_date       date                                    NOT NULL,
    facility_id        VARCHAR(50)                             NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by         BIGINT,
    CONSTRAINT pk_vaccine_batches PRIMARY KEY (id)
);

-- Create Vaccinations Table
CREATE TABLE vaccinations
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patient_id        UUID                                    NOT NULL,
    batch_id          BIGINT                                  NOT NULL,
    nurse_id          BIGINT                                  NOT NULL,
    vaccine_name      VARCHAR(100)                            NOT NULL,
    dose_number       INTEGER                                 NOT NULL,
    date_administered date                                    NOT NULL,
    facility_id       VARCHAR(50)                             NOT NULL,
    notes             VARCHAR(500),
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_vaccinations PRIMARY KEY (id)
);

-- Create Campaigns Table
CREATE TABLE campaigns
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name               VARCHAR(200)                            NOT NULL,
    description        TEXT,
    vaccine_name       VARCHAR(100)                            NOT NULL,
    target_age_group   VARCHAR(100),
    start_date         date                                    NOT NULL,
    end_date           date                                    NOT NULL,
    target_population  INTEGER,
    vaccinated_count   INTEGER,
    status             VARCHAR(20)                             NOT NULL,
    facility_id        VARCHAR(50),
    district_id        VARCHAR(50),
    national_id        VARCHAR(50),
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by         BIGINT,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_campaigns PRIMARY KEY (id)
);

-- Create Offline Sync Queue Table
CREATE TABLE offline_sync_queue
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id         BIGINT                                  NOT NULL,
    entity_type     VARCHAR(50)                             NOT NULL,
    entity_id       VARCHAR(100)                            NOT NULL,
    operation_type  VARCHAR(20)                             NOT NULL,
    entity_data     TEXT,
    sync_status     VARCHAR(20)                             NOT NULL,
    retry_count     INTEGER,
    error_message   TEXT,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    synced_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_offline_sync_queue PRIMARY KEY (id)
);

-- Create Appointments Table (missing - required by Hibernate entity)
CREATE TABLE appointments
(
    id               UUID                        NOT NULL,
    patient_id       UUID                        NOT NULL,
    facility_id      VARCHAR(50)                 NOT NULL,
    vaccine_name     VARCHAR(100)                NOT NULL,
    dose_number      INTEGER                     NOT NULL,
    appointment_date DATE                        NOT NULL,
    appointment_time TIME,
    status           VARCHAR(20)                 NOT NULL,
    notes            VARCHAR(500),
    sms_sent         BOOLEAN                     NOT NULL DEFAULT false,
    sms_sent_at      TIMESTAMP WITHOUT TIME ZONE,
    created_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by       BIGINT,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_appointments PRIMARY KEY (id)
);


-- Add Unique Constraints
ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE vaccine_batches
    ADD CONSTRAINT uk_batch_facility UNIQUE (batch_number, facility_id);

-- Create Indexes
CREATE INDEX idx_username ON users (username);
CREATE INDEX idx_role ON users (role);
CREATE INDEX idx_facility_id ON users (facility_id);

CREATE INDEX idx_facility_patients ON patients (facility_id);
CREATE INDEX idx_patient_dob ON patients (date_of_birth);
CREATE INDEX idx_patient_deleted ON patients (deleted);

CREATE INDEX idx_facility_batches ON vaccine_batches (facility_id);
CREATE INDEX idx_vaccine_name ON vaccine_batches (vaccine_name);
CREATE INDEX idx_expiry_date ON vaccine_batches (expiry_date);

CREATE INDEX idx_patient_vaccinations ON vaccinations (patient_id);
CREATE INDEX idx_batch_vaccinations ON vaccinations (batch_id);
CREATE INDEX idx_facility_vaccinations ON vaccinations (facility_id);
CREATE INDEX idx_vaccination_date ON vaccinations (date_administered);

CREATE INDEX idx_campaign_dates ON campaigns (start_date, end_date);
CREATE INDEX idx_campaign_status ON campaigns (status);
CREATE INDEX idx_campaign_facility ON campaigns (facility_id);

CREATE INDEX idx_sync_status ON offline_sync_queue (sync_status);
CREATE INDEX idx_sync_user ON offline_sync_queue (user_id);
CREATE INDEX idx_sync_created ON offline_sync_queue (created_at);

-- Insert Default Users (passwords are BCrypt hashed with strength 12)
-- Password for all users: "Password123!" (BCrypt hashed)
INSERT INTO users (username, password, email, full_name, role, facility_id, district_id, active, locked, failed_login_attempts, created_at, deleted)
VALUES 
    ('health.worker', '$2a$12$.4qFisHXCJZsQog8d8iYveyZJg7dVasFEy1/zJzShHvvkDubdpwqi', 'health.worker@immunization.com', 'Health Worker', 'HEALTH_WORKER', 'FAC001', NULL, true, false, 0, CURRENT_TIMESTAMP, false),
    ('facility.manager', '$2a$12$.4qFisHXCJZsQog8d8iYveyZJg7dVasFEy1/zJzShHvvkDubdpwqi', 'facility.manager@immunization.com', 'Facility Manager', 'FACILITY_MANAGER', 'FAC001', 'DIST001', true, false, 0, CURRENT_TIMESTAMP, false),
    ('gov.official', '$2a$12$.4qFisHXCJZsQog8d8iYveyZJg7dVasFEy1/zJzShHvvkDubdpwqi', 'gov.official@immunization.com', 'Government Official', 'GOVERNMENT_OFFICIAL', NULL, NULL, true, false, 0, CURRENT_TIMESTAMP, false);

-- Add comprehensive test data for all facilities and users

-- =====================================================
-- 1. ADD MORE FACILITIES AND DISTRICTS
-- =====================================================

-- Note: Users already exist (health.worker, facility.manager, gov.official)
-- Adding more facilities for better testing

-- Add facility manager for FAC002
INSERT INTO users (username, password, email, full_name, role, facility_id, district_id, active, locked, failed_login_attempts, created_at, deleted)
VALUES 
    ('manager.fac002', '$2a$12$.4qFisHXCJZsQog8d8iYveyZJg7dVasFEy1/zJzShHvvkDubdpwqi', 'manager.fac002@immunization.com', 'Manager FAC002', 'FACILITY_MANAGER', 'FAC002', 'DIST002', true, false, 0, CURRENT_TIMESTAMP, false),
    ('worker.fac002', '$2a$12$.4qFisHXCJZsQog8d8iYveyZJg7dVasFEy1/zJzShHvvkDubdpwqi', 'worker.fac002@immunization.com', 'Health Worker FAC002', 'HEALTH_WORKER', 'FAC002', NULL, true, false, 0, CURRENT_TIMESTAMP, false)
ON CONFLICT (username) DO NOTHING;

-- =====================================================
-- 2. ADD VACCINE BATCHES FOR FACILITY FAC001
-- =====================================================

INSERT INTO vaccine_batches (batch_number, vaccine_name, manufacturer, quantity_received, quantity_remaining, expiry_date, receipt_date, facility_id, created_at, created_by)
VALUES 
    -- Active batches with good stock
    ('BCG-2024-001', 'BCG', 'Serum Institute of India', 500, 450, '2025-12-31', '2024-01-15', 'FAC001', CURRENT_TIMESTAMP, 1),
    ('OPV-2024-001', 'OPV', 'Bio-Manguinhos', 1000, 850, '2025-11-30', '2024-02-01', 'FAC001', CURRENT_TIMESTAMP, 1),
    ('DTP-2024-001', 'DTP', 'Bharat Biotech', 750, 600, '2025-10-31', '2024-03-10', 'FAC001', CURRENT_TIMESTAMP, 1),
    ('MEASLES-2024-001', 'Measles', 'Serum Institute of India', 600, 500, '2025-09-30', '2024-04-05', 'FAC001', CURRENT_TIMESTAMP, 1),
    ('HEPATITIS-2024-001', 'Hepatitis B', 'GlaxoSmithKline', 800, 700, '2026-01-31', '2024-05-20', 'FAC001', CURRENT_TIMESTAMP, 1),
    
    -- Batches expiring soon (within 30 days)
    ('BCG-2024-002', 'BCG', 'Serum Institute of India', 300, 280, '2025-01-10', '2024-06-01', 'FAC001', CURRENT_TIMESTAMP, 1),
    ('OPV-2024-002', 'OPV', 'Bio-Manguinhos', 400, 350, '2025-01-05', '2024-06-15', 'FAC001', CURRENT_TIMESTAMP, 1),
    
    -- Low stock batches
    ('DTP-2024-002', 'DTP', 'Bharat Biotech', 200, 45, '2025-08-31', '2024-07-01', 'FAC001', CURRENT_TIMESTAMP, 1),
    ('MEASLES-2024-002', 'Measles', 'Serum Institute of India', 150, 30, '2025-07-31', '2024-07-15', 'FAC001', CURRENT_TIMESTAMP, 1),
    
    -- Recently expired batch
    ('POLIO-2023-001', 'Polio', 'Sanofi Pasteur', 500, 50, '2024-11-30', '2023-11-01', 'FAC001', CURRENT_TIMESTAMP, 1)
ON CONFLICT (batch_number, facility_id) DO NOTHING;

-- =====================================================
-- 3. ADD VACCINE BATCHES FOR FACILITY FAC002
-- =====================================================

INSERT INTO vaccine_batches (batch_number, vaccine_name, manufacturer, quantity_received, quantity_remaining, expiry_date, receipt_date, facility_id, created_at, created_by)
VALUES 
    ('BCG-2024-FAC2-001', 'BCG', 'Serum Institute of India', 400, 380, '2025-12-31', '2024-02-01', 'FAC002', CURRENT_TIMESTAMP, 3),
    ('OPV-2024-FAC2-001', 'OPV', 'Bio-Manguinhos', 800, 720, '2025-11-30', '2024-02-15', 'FAC002', CURRENT_TIMESTAMP, 3),
    ('DTP-2024-FAC2-001', 'DTP', 'Bharat Biotech', 600, 550, '2025-10-31', '2024-03-01', 'FAC002', CURRENT_TIMESTAMP, 3),
    ('MEASLES-2024-FAC2-001', 'Measles', 'Serum Institute of India', 500, 450, '2025-09-30', '2024-03-15', 'FAC002', CURRENT_TIMESTAMP, 3),
    ('HEPATITIS-2024-FAC2-001', 'Hepatitis B', 'GlaxoSmithKline', 700, 650, '2026-02-28', '2024-04-01', 'FAC002', CURRENT_TIMESTAMP, 3)
ON CONFLICT (batch_number, facility_id) DO NOTHING;

-- =====================================================
-- 4. ADD PATIENTS FOR FACILITY FAC001
-- =====================================================

INSERT INTO patients (id, full_name, date_of_birth, gender, guardian_name, phone_number, address, facility_id, deleted, created_at, created_by)
VALUES 
    (gen_random_uuid(), 'Baby John Doe', '2024-10-15', 'Male', 'Jane Doe', '0712345001', '123 Main Street, Nairobi', 'FAC001', false, CURRENT_TIMESTAMP, 1),
    (gen_random_uuid(), 'Baby Mary Smith', '2024-09-20', 'Female', 'Sarah Smith', '0712345002', '456 Oak Avenue, Nairobi', 'FAC001', false, CURRENT_TIMESTAMP, 1),
    (gen_random_uuid(), 'Baby David Johnson', '2024-08-10', 'Male', 'Lisa Johnson', '0712345003', '789 Pine Road, Nairobi', 'FAC001', false, CURRENT_TIMESTAMP, 1),
    (gen_random_uuid(), 'Baby Emma Wilson', '2024-07-05', 'Female', 'Robert Wilson', '0712345004', '321 Elm Street, Nairobi', 'FAC001', false, CURRENT_TIMESTAMP, 1),
    (gen_random_uuid(), 'Baby James Brown', '2024-11-01', 'Male', 'Patricia Brown', '0712345005', '654 Maple Drive, Nairobi', 'FAC001', false, CURRENT_TIMESTAMP, 1),
    (gen_random_uuid(), 'Baby Sophia Davis', '2024-06-15', 'Female', 'Michael Davis', '0712345006', '987 Cedar Lane, Nairobi', 'FAC001', false, CURRENT_TIMESTAMP, 1),
    (gen_random_uuid(), 'Baby Oliver Martinez', '2024-05-20', 'Male', 'Jennifer Martinez', '0712345007', '147 Birch Court, Nairobi', 'FAC001', false, CURRENT_TIMESTAMP, 1),
    (gen_random_uuid(), 'Baby Isabella Garcia', '2024-04-25', 'Female', 'William Garcia', '0712345008', '258 Spruce Way, Nairobi', 'FAC001', false, CURRENT_TIMESTAMP, 1),
    (gen_random_uuid(), 'Baby Liam Rodriguez', '2024-03-30', 'Male', 'Elizabeth Rodriguez', '0712345009', '369 Willow Path, Nairobi', 'FAC001', false, CURRENT_TIMESTAMP, 1),
    (gen_random_uuid(), 'Baby Ava Lopez', '2024-02-14', 'Female', 'James Lopez', '0712345010', '741 Ash Boulevard, Nairobi', 'FAC001', false, CURRENT_TIMESTAMP, 1);

-- =====================================================
-- 5. ADD PATIENTS FOR FACILITY FAC002
-- =====================================================

INSERT INTO patients (id, full_name, date_of_birth, gender, guardian_name, phone_number, address, facility_id, deleted, created_at, created_by)
VALUES 
    (gen_random_uuid(), 'Baby Noah Anderson', '2024-09-05', 'Male', 'Mary Anderson', '0722345001', '111 River Road, Mombasa', 'FAC002', false, CURRENT_TIMESTAMP, 4),
    (gen_random_uuid(), 'Baby Mia Thomas', '2024-08-12', 'Female', 'David Thomas', '0722345002', '222 Lake Street, Mombasa', 'FAC002', false, CURRENT_TIMESTAMP, 4),
    (gen_random_uuid(), 'Baby Ethan Taylor', '2024-07-18', 'Male', 'Nancy Taylor', '0722345003', '333 Ocean Drive, Mombasa', 'FAC002', false, CURRENT_TIMESTAMP, 4),
    (gen_random_uuid(), 'Baby Charlotte Moore', '2024-06-22', 'Female', 'Christopher Moore', '0722345004', '444 Beach Avenue, Mombasa', 'FAC002', false, CURRENT_TIMESTAMP, 4),
    (gen_random_uuid(), 'Baby Lucas Jackson', '2024-10-30', 'Male', 'Linda Jackson', '0722345005', '555 Harbor Way, Mombasa', 'FAC002', false, CURRENT_TIMESTAMP, 4);

-- =====================================================
-- 6. ADD VACCINATIONS (Recent activity)
-- =====================================================

-- Store patient IDs in temporary variables (we'll use the first few patients)
-- Note: In production, you'd fetch actual patient IDs. For this migration, we'll use a subquery.

-- Vaccinations for FAC001 patients
INSERT INTO vaccinations (patient_id, batch_id, nurse_id, vaccine_name, dose_number, date_administered, facility_id, notes, created_at)
SELECT 
    p.id,
    1, -- BCG-2024-001 batch_id
    1, -- health.worker user_id
    'BCG',
    1,
    CURRENT_DATE - INTERVAL '5 days',
    'FAC001',
    'First dose administered successfully',
    CURRENT_TIMESTAMP
FROM patients p
WHERE p.facility_id = 'FAC001'
LIMIT 5;

INSERT INTO vaccinations (patient_id, batch_id, nurse_id, vaccine_name, dose_number, date_administered, facility_id, notes, created_at)
SELECT 
    p.id,
    2, -- OPV-2024-001 batch_id
    1, -- health.worker user_id
    'OPV',
    1,
    CURRENT_DATE - INTERVAL '3 days',
    'FAC001',
    'OPV dose 1 - no adverse reactions',
    CURRENT_TIMESTAMP
FROM patients p
WHERE p.facility_id = 'FAC001'
LIMIT 4;

INSERT INTO vaccinations (patient_id, batch_id, nurse_id, vaccine_name, dose_number, date_administered, facility_id, notes, created_at)
SELECT 
    p.id,
    3, -- DTP-2024-001 batch_id
    1, -- health.worker user_id
    'DTP',
    1,
    CURRENT_DATE - INTERVAL '1 day',
    'FAC001',
    'DTP vaccination completed',
    CURRENT_TIMESTAMP
FROM patients p
WHERE p.facility_id = 'FAC001'
LIMIT 3;

-- Vaccinations for FAC002 patients
INSERT INTO vaccinations (patient_id, batch_id, nurse_id, vaccine_name, dose_number, date_administered, facility_id, notes, created_at)
SELECT 
    p.id,
    11, -- BCG-2024-FAC2-001 batch_id
    5, -- worker.fac002 user_id
    'BCG',
    1,
    CURRENT_DATE - INTERVAL '4 days',
    'FAC002',
    'BCG administered - birth dose',
    CURRENT_TIMESTAMP
FROM patients p
WHERE p.facility_id = 'FAC002'
LIMIT 3;

-- =====================================================
-- 7. ADD CAMPAIGNS (Active, Scheduled, and Completed)
-- =====================================================

-- Only insert campaigns if they don't already exist (check by name)
INSERT INTO campaigns (name, description, vaccine_name, target_age_group, start_date, end_date, target_population, vaccinated_count, status, facility_id, district_id, created_at, created_by)
SELECT 'BCG Newborn Campaign 2024', 'BCG vaccination for all newborns in the facility', 'BCG', '0-1 months', '2024-11-01', '2025-01-31', 500, 245, 'ACTIVE', 'FAC001', 'DIST001', CURRENT_TIMESTAMP, 2
WHERE NOT EXISTS (SELECT 1 FROM campaigns WHERE name = 'BCG Newborn Campaign 2024');

INSERT INTO campaigns (name, description, vaccine_name, target_age_group, start_date, end_date, target_population, vaccinated_count, status, facility_id, district_id, created_at, created_by)
SELECT 'Measles Outbreak Response', 'Emergency measles vaccination campaign', 'Measles', '9-59 months', '2024-12-01', '2025-02-28', 1000, 387, 'ACTIVE', 'FAC001', 'DIST001', CURRENT_TIMESTAMP, 2
WHERE NOT EXISTS (SELECT 1 FROM campaigns WHERE name = 'Measles Outbreak Response');

INSERT INTO campaigns (name, description, vaccine_name, target_age_group, start_date, end_date, target_population, vaccinated_count, status, facility_id, district_id, created_at, created_by)
SELECT 'DTP Catch-up Campaign', 'DTP vaccination for missed doses', 'DTP', '6-18 months', '2024-11-15', '2025-01-15', 750, 523, 'ACTIVE', 'FAC002', 'DIST002', CURRENT_TIMESTAMP, 4
WHERE NOT EXISTS (SELECT 1 FROM campaigns WHERE name = 'DTP Catch-up Campaign');

INSERT INTO campaigns (name, description, vaccine_name, target_age_group, start_date, end_date, target_population, vaccinated_count, status, facility_id, district_id, created_at, created_by)
SELECT 'Polio National Immunization Day', 'National polio eradication campaign', 'OPV', '0-5 years', '2025-01-15', '2025-01-17', 5000, 0, 'PLANNED', NULL, NULL, CURRENT_TIMESTAMP, 3
WHERE NOT EXISTS (SELECT 1 FROM campaigns WHERE name = 'Polio National Immunization Day');

INSERT INTO campaigns (name, description, vaccine_name, target_age_group, start_date, end_date, target_population, vaccinated_count, status, facility_id, district_id, created_at, created_by)
SELECT 'Hepatitis B Birth Dose', 'Hepatitis B vaccination at birth', 'Hepatitis B', '0-1 months', '2025-02-01', '2025-04-30', 800, 0, 'PLANNED', 'FAC001', 'DIST001', CURRENT_TIMESTAMP, 2
WHERE NOT EXISTS (SELECT 1 FROM campaigns WHERE name = 'Hepatitis B Birth Dose');

INSERT INTO campaigns (name, description, vaccine_name, target_age_group, start_date, end_date, target_population, vaccinated_count, status, facility_id, district_id, created_at, created_by)
SELECT 'Q3 Routine Immunization', 'Quarterly routine immunization drive', 'Multiple', 'All ages', '2024-07-01', '2024-09-30', 2000, 1847, 'COMPLETED', 'FAC001', 'DIST001', CURRENT_TIMESTAMP - INTERVAL '90 days', 2
WHERE NOT EXISTS (SELECT 1 FROM campaigns WHERE name = 'Q3 Routine Immunization');

INSERT INTO campaigns (name, description, vaccine_name, target_age_group, start_date, end_date, target_population, vaccinated_count, status, facility_id, district_id, created_at, created_by)
SELECT 'Back-to-School Vaccination', 'School entry vaccination campaign', 'Multiple', '5-6 years', '2024-08-01', '2024-08-31', 1500, 1423, 'COMPLETED', 'FAC002', 'DIST002', CURRENT_TIMESTAMP - INTERVAL '60 days', 4
WHERE NOT EXISTS (SELECT 1 FROM campaigns WHERE name = 'Back-to-School Vaccination');

-- =====================================================
-- 8. UPDATE BATCH QUANTITIES TO REFLECT VACCINATIONS
-- =====================================================

-- Update BCG-2024-001 (used 50 doses)
UPDATE vaccine_batches SET quantity_remaining = quantity_remaining - 50 
WHERE batch_number = 'BCG-2024-001' AND quantity_remaining >= 50;

-- Update OPV-2024-001 (used 40 doses)
UPDATE vaccine_batches SET quantity_remaining = quantity_remaining - 40 
WHERE batch_number = 'OPV-2024-001' AND quantity_remaining >= 40;

-- Update DTP-2024-001 (used 30 doses)
UPDATE vaccine_batches SET quantity_remaining = quantity_remaining - 30 
WHERE batch_number = 'DTP-2024-001' AND quantity_remaining >= 30;

-- Update BCG-2024-FAC2-001 (used 30 doses)
UPDATE vaccine_batches SET quantity_remaining = quantity_remaining - 30 
WHERE batch_number = 'BCG-2024-FAC2-001' AND quantity_remaining >= 30;
