-- Create Users Table
CREATE TABLE users
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username               VARCHAR(50)                             NOT NULL,
    password               VARCHAR(255)                            NOT NULL,
    email                  VARCHAR(255)                            NOT NULL,
    full_name              VARCHAR(255)                            NOT NULL,
    role                   VARCHAR(50)                             NOT NULL,
    facility_id            VARCHAR(50),
    district_id            VARCHAR(50),
    national_id            VARCHAR(50),
    active                 BOOLEAN                                 NOT NULL,
    locked                 BOOLEAN                                 NOT NULL,
    failed_login_attempts  INTEGER                                 NOT NULL,
    created_at             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by             BIGINT,
    deleted                BOOLEAN                                 NOT NULL,
    deleted_at             TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- Create Patients Table
CREATE TABLE patients
(
    id            UUID                        NOT NULL,
    full_name     VARCHAR(255)                NOT NULL,
    date_of_birth date                        NOT NULL,
    gender        VARCHAR(10)                 NOT NULL,
    guardian_name VARCHAR(255),
    phone_number  VARCHAR(20),
    address       TEXT,
    facility_id   VARCHAR(50)                 NOT NULL,
    deleted       BOOLEAN                     NOT NULL,
    deleted_at    TIMESTAMP WITHOUT TIME ZONE,
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by    BIGINT,
    CONSTRAINT pk_patients PRIMARY KEY (id)
);

-- Create Vaccine Batches Table
CREATE TABLE vaccine_batches
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    batch_number       VARCHAR(50)                             NOT NULL,
    vaccine_name       VARCHAR(100)                            NOT NULL,
    manufacturer       VARCHAR(100)                            NOT NULL,
    quantity_received  INTEGER                                 NOT NULL,
    quantity_remaining INTEGER                                 NOT NULL,
    expiry_date        date                                    NOT NULL,
    receipt_date       date                                    NOT NULL,
    facility_id        VARCHAR(50)                             NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by         BIGINT,
    CONSTRAINT pk_vaccine_batches PRIMARY KEY (id)
);

-- Create Vaccinations Table
CREATE TABLE vaccinations
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patient_id        UUID                                    NOT NULL,
    batch_id          BIGINT                                  NOT NULL,
    nurse_id          BIGINT                                  NOT NULL,
    vaccine_name      VARCHAR(100)                            NOT NULL,
    dose_number       INTEGER                                 NOT NULL,
    date_administered date                                    NOT NULL,
    facility_id       VARCHAR(50)                             NOT NULL,
    notes             VARCHAR(500),
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_vaccinations PRIMARY KEY (id)
);

-- Create Campaigns Table
CREATE TABLE campaigns
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name               VARCHAR(200)                            NOT NULL,
    description        TEXT,
    vaccine_name       VARCHAR(100)                            NOT NULL,
    target_age_group   VARCHAR(100),
    start_date         date                                    NOT NULL,
    end_date           date                                    NOT NULL,
    target_population  INTEGER,
    vaccinated_count   INTEGER,
    status             VARCHAR(20)                             NOT NULL,
    facility_id        VARCHAR(50),
    district_id        VARCHAR(50),
    national_id        VARCHAR(50),
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by         BIGINT,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_campaigns PRIMARY KEY (id)
);

-- Create Offline Sync Queue Table
CREATE TABLE offline_sync_queue
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id         BIGINT                                  NOT NULL,
    entity_type     VARCHAR(50)                             NOT NULL,
    entity_id       VARCHAR(100)                            NOT NULL,
    operation_type  VARCHAR(20)                             NOT NULL,
    entity_data     TEXT,
    sync_status     VARCHAR(20)                             NOT NULL,
    retry_count     INTEGER,
    error_message   TEXT,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    synced_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_offline_sync_queue PRIMARY KEY (id)
);

-- Add Unique Constraints
ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE vaccine_batches
    ADD CONSTRAINT uk_batch_facility UNIQUE (batch_number, facility_id);

-- Create Indexes
CREATE INDEX idx_username ON users (username);
CREATE INDEX idx_role ON users (role);
CREATE INDEX idx_facility_id ON users (facility_id);

CREATE INDEX idx_facility_patients ON patients (facility_id);
CREATE INDEX idx_patient_dob ON patients (date_of_birth);
CREATE INDEX idx_patient_deleted ON patients (deleted);

CREATE INDEX idx_facility_batches ON vaccine_batches (facility_id);
CREATE INDEX idx_vaccine_name ON vaccine_batches (vaccine_name);
CREATE INDEX idx_expiry_date ON vaccine_batches (expiry_date);

CREATE INDEX idx_patient_vaccinations ON vaccinations (patient_id);
CREATE INDEX idx_batch_vaccinations ON vaccinations (batch_id);
CREATE INDEX idx_facility_vaccinations ON vaccinations (facility_id);
CREATE INDEX idx_vaccination_date ON vaccinations (date_administered);

CREATE INDEX idx_campaign_dates ON campaigns (start_date, end_date);
CREATE INDEX idx_campaign_status ON campaigns (status);
CREATE INDEX idx_campaign_facility ON campaigns (facility_id);

CREATE INDEX idx_sync_status ON offline_sync_queue (sync_status);
CREATE INDEX idx_sync_user ON offline_sync_queue (user_id);
CREATE INDEX idx_sync_created ON offline_sync_queue (created_at);

-- Insert Default Users (passwords are BCrypt hashed with strength 12)
-- Password for all users: "Password123!" (BCrypt hashed)
INSERT INTO users (username, password, email, full_name, role, facility_id, district_id, active, locked, failed_login_attempts, created_at, deleted)
VALUES 
    ('health.worker', '$$2a$$12$$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5GyYIBdCRX7Ze', 'health.worker@immunization.com', 'Health Worker', 'HEALTH_WORKER', 'FAC001', NULL, true, false, 0, CURRENT_TIMESTAMP, false),
    ('facility.manager', '$$2a$$12$$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5GyYIBdCRX7Ze', 'facility.manager@immunization.com', 'Facility Manager', 'FACILITY_MANAGER', 'FAC001', 'DIST001', true, false, 0, CURRENT_TIMESTAMP, false),
    ('gov.official', '$$2a$$12$$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5GyYIBdCRX7Ze', 'gov.official@immunization.com', 'Government Official', 'GOVERNMENT_OFFICIAL', NULL, NULL, true, false, 0, CURRENT_TIMESTAMP, false);