-- Create Facilities Table
CREATE TABLE IF NOT EXISTS facilities
(
    id              VARCHAR(50) PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    type            VARCHAR(50) NOT NULL, -- 'HOSPITAL', 'HEALTH_CENTER', 'CLINIC'
    district_id     VARCHAR(50),
    county          VARCHAR(100),
    address         TEXT,
    phone_number    VARCHAR(20),
    email           VARCHAR(255),
    capacity        INTEGER,
    active          BOOLEAN NOT NULL DEFAULT true,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITHOUT TIME ZONE
);

-- Create Districts Table
CREATE TABLE IF NOT EXISTS districts
(
    id              VARCHAR(50) PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    county          VARCHAR(100) NOT NULL,
    population      INTEGER,
    active          BOOLEAN NOT NULL DEFAULT true,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create Vaccines Master Table
CREATE TABLE IF NOT EXISTS vaccines
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(100) NOT NULL UNIQUE,
    full_name           VARCHAR(255),
    manufacturer        VARCHAR(100),
    description         TEXT,
    dosage_ml           DECIMAL(5,2),
    doses_required      INTEGER NOT NULL DEFAULT 1,
    dose_interval_days  INTEGER, -- Interval between doses
    minimum_age_days    INTEGER, -- Minimum age for first dose
    storage_temp_min    DECIMAL(5,2), -- Minimum storage temperature (Celsius)
    storage_temp_max    DECIMAL(5,2), -- Maximum storage temperature (Celsius)
    active              BOOLEAN NOT NULL DEFAULT true,
    created_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create Dose Schedule Table
CREATE TABLE IF NOT EXISTS dose_schedules
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vaccine_id      BIGINT NOT NULL,
    dose_number     INTEGER NOT NULL,
    age_months      INTEGER NOT NULL, -- Recommended age in months
    description     VARCHAR(255),
    CONSTRAINT fk_dose_vaccine FOREIGN KEY (vaccine_id) REFERENCES vaccines(id) ON DELETE CASCADE,
    CONSTRAINT uk_vaccine_dose UNIQUE (vaccine_id, dose_number)
);

-- Create Stock Alerts Table
CREATE TABLE IF NOT EXISTS stock_alerts
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_id     VARCHAR(50) NOT NULL,
    batch_id        BIGINT,
    alert_type      VARCHAR(50) NOT NULL, -- 'LOW_STOCK', 'EXPIRING_SOON', 'EXPIRED', 'OUT_OF_STOCK'
    severity        VARCHAR(20) NOT NULL, -- 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'
    message         TEXT NOT NULL,
    is_resolved     BOOLEAN NOT NULL DEFAULT false,
    resolved_at     TIMESTAMP WITHOUT TIME ZONE,
    resolved_by     BIGINT,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_alert_batch FOREIGN KEY (batch_id) REFERENCES vaccine_batches(id) ON DELETE SET NULL
);

-- Create Audit Log Table
CREATE TABLE IF NOT EXISTS audit_logs
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    action          VARCHAR(100) NOT NULL,
    entity_type     VARCHAR(50) NOT NULL, -- 'USER', 'PATIENT', 'VACCINATION', 'BATCH', 'CAMPAIGN'
    entity_id       VARCHAR(100),
    old_value       TEXT,
    new_value       TEXT,
    ip_address      VARCHAR(50),
    user_agent      TEXT,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Insert Sample Facilities
INSERT INTO facilities (id, name, type, district_id, county, address, phone_number, email, capacity, active) VALUES
('FAC001', 'Nairobi Central Health Center', 'HEALTH_CENTER', 'DIST001', 'Nairobi', 'Kenyatta Avenue, Nairobi', '+254712345001', 'nairobi.central@health.ke', 200, true),
('FAC002', 'Mombasa Coast Hospital', 'HOSPITAL', 'DIST002', 'Mombasa', 'Moi Avenue, Mombasa', '+254712345002', 'mombasa.coast@health.ke', 500, true),
('FAC003', 'Kisumu Lake View Clinic', 'CLINIC', 'DIST003', 'Kisumu', 'Oginga Odinga Road, Kisumu', '+254712345003', 'kisumu.lakeview@health.ke', 100, true),
('FAC004', 'Nakuru Rift Valley Health Center', 'HEALTH_CENTER', 'DIST004', 'Nakuru', 'Kenyatta Avenue, Nakuru', '+254712345004', 'nakuru.riftvalley@health.ke', 150, true),
('FAC005', 'Eldoret West Hospital', 'HOSPITAL', 'DIST005', 'Uasin Gishu', 'Uganda Road, Eldoret', '+254712345005', 'eldoret.west@health.ke', 400, true)
ON CONFLICT (id) DO NOTHING;

-- Insert Sample Districts
INSERT INTO districts (id, name, county, population) VALUES
('DIST001', 'Nairobi Central', 'Nairobi', 500000),
('DIST002', 'Mombasa Island', 'Mombasa', 300000),
('DIST003', 'Kisumu Central', 'Kisumu', 250000),
('DIST004', 'Nakuru Town', 'Nakuru', 350000),
('DIST005', 'Eldoret West', 'Uasin Gishu', 280000)
ON CONFLICT (id) DO NOTHING;

-- Insert Standard Vaccines
INSERT INTO vaccines (name, full_name, manufacturer, description, dosage_ml, doses_required, dose_interval_days, minimum_age_days, storage_temp_min, storage_temp_max) VALUES
('BCG', 'Bacillus Calmette-Guérin', 'Serum Institute of India', 'Tuberculosis vaccine', 0.05, 1, 0, 0, 2, 8),
('OPV', 'Oral Polio Vaccine', 'Bio-Manguinhos', 'Polio vaccine (oral)', 2.00, 4, 30, 0, 2, 8),
('DTP', 'Diphtheria, Tetanus, Pertussis', 'Bharat Biotech', 'Combined vaccine for diphtheria, tetanus, and pertussis', 0.5, 3, 30, 42, 2, 8),
('Measles', 'Measles Vaccine', 'Serum Institute of India', 'Measles protection vaccine', 0.5, 2, 180, 270, 2, 8),
('Hepatitis B', 'Hepatitis B Vaccine', 'GlaxoSmithKline', 'Hepatitis B protection', 0.5, 3, 30, 0, 2, 8),
('Rotavirus', 'Rotavirus Vaccine', 'GlaxoSmithKline', 'Protects against rotavirus gastroenteritis', 1.0, 2, 30, 42, 2, 8),
('Pneumococcal', 'Pneumococcal Conjugate Vaccine (PCV)', 'Pfizer', 'Protects against pneumococcal disease', 0.5, 3, 30, 42, 2, 8),
('Yellow Fever', 'Yellow Fever Vaccine', 'Sanofi Pasteur', 'Yellow fever protection', 0.5, 1, 0, 270, 2, 8)
ON CONFLICT (name) DO NOTHING;

-- Insert Dose Schedules
INSERT INTO dose_schedules (vaccine_id, dose_number, age_months, description) VALUES
-- BCG (single dose at birth)
((SELECT id FROM vaccines WHERE name = 'BCG'), 1, 0, 'At birth'),

-- OPV (4 doses)
((SELECT id FROM vaccines WHERE name = 'OPV'), 1, 0, 'At birth'),
((SELECT id FROM vaccines WHERE name = 'OPV'), 2, 1, '6 weeks'),
((SELECT id FROM vaccines WHERE name = 'OPV'), 3, 2, '10 weeks'),
((SELECT id FROM vaccines WHERE name = 'OPV'), 4, 3, '14 weeks'),

-- DTP (3 doses)
((SELECT id FROM vaccines WHERE name = 'DTP'), 1, 1, '6 weeks'),
((SELECT id FROM vaccines WHERE name = 'DTP'), 2, 2, '10 weeks'),
((SELECT id FROM vaccines WHERE name = 'DTP'), 3, 3, '14 weeks'),

-- Measles (2 doses)
((SELECT id FROM vaccines WHERE name = 'Measles'), 1, 9, '9 months'),
((SELECT id FROM vaccines WHERE name = 'Measles'), 2, 18, '18 months'),

-- Hepatitis B (3 doses)
((SELECT id FROM vaccines WHERE name = 'Hepatitis B'), 1, 0, 'At birth'),
((SELECT id FROM vaccines WHERE name = 'Hepatitis B'), 2, 1, '6 weeks'),
((SELECT id FROM vaccines WHERE name = 'Hepatitis B'), 3, 2, '14 weeks'),

-- Rotavirus (2 doses)
((SELECT id FROM vaccines WHERE name = 'Rotavirus'), 1, 1, '6 weeks'),
((SELECT id FROM vaccines WHERE name = 'Rotavirus'), 2, 2, '10 weeks'),

-- Pneumococcal (3 doses)
((SELECT id FROM vaccines WHERE name = 'Pneumococcal'), 1, 1, '6 weeks'),
((SELECT id FROM vaccines WHERE name = 'Pneumococcal'), 2, 2, '10 weeks'),
((SELECT id FROM vaccines WHERE name = 'Pneumococcal'), 3, 3, '14 weeks'),

-- Yellow Fever (single dose at 9 months)
((SELECT id FROM vaccines WHERE name = 'Yellow Fever'), 1, 9, '9 months')
ON CONFLICT (vaccine_id, dose_number) DO NOTHING;

-- Create Indexes for new tables
CREATE INDEX IF NOT EXISTS idx_facilities_district ON facilities(district_id);
CREATE INDEX IF NOT EXISTS idx_facilities_active ON facilities(active);
CREATE INDEX IF NOT EXISTS idx_districts_county ON districts(county);
CREATE INDEX IF NOT EXISTS idx_vaccines_active ON vaccines(active);
CREATE INDEX IF NOT EXISTS idx_stock_alerts_facility ON stock_alerts(facility_id);
CREATE INDEX IF NOT EXISTS idx_stock_alerts_resolved ON stock_alerts(is_resolved);
CREATE INDEX IF NOT EXISTS idx_stock_alerts_created ON stock_alerts(created_at);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user ON audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON audit_logs(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created ON audit_logs(created_at);

-- Add Foreign Key Constraints to existing tables
ALTER TABLE users ADD CONSTRAINT IF NOT EXISTS fk_users_facility 
    FOREIGN KEY (facility_id) REFERENCES facilities(id) ON DELETE SET NULL;

ALTER TABLE patients ADD CONSTRAINT IF NOT EXISTS fk_patients_facility 
    FOREIGN KEY (facility_id) REFERENCES facilities(id) ON DELETE CASCADE;

ALTER TABLE vaccine_batches ADD CONSTRAINT IF NOT EXISTS fk_batches_facility 
    FOREIGN KEY (facility_id) REFERENCES facilities(id) ON DELETE CASCADE;

ALTER TABLE vaccinations ADD CONSTRAINT IF NOT EXISTS fk_vaccinations_patient 
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE;

ALTER TABLE vaccinations ADD CONSTRAINT IF NOT EXISTS fk_vaccinations_batch 
    FOREIGN KEY (batch_id) REFERENCES vaccine_batches(id) ON DELETE RESTRICT;

ALTER TABLE vaccinations ADD CONSTRAINT IF NOT EXISTS fk_vaccinations_nurse 
    FOREIGN KEY (nurse_id) REFERENCES users(id) ON DELETE RESTRICT;

ALTER TABLE campaigns ADD CONSTRAINT IF NOT EXISTS fk_campaigns_facility 
    FOREIGN KEY (facility_id) REFERENCES facilities(id) ON DELETE CASCADE;

ALTER TABLE campaigns ADD CONSTRAINT IF NOT EXISTS fk_campaigns_creator 
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL;
