-- Create Adverse Events Table
CREATE TABLE IF NOT EXISTS adverse_events
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id      UUID NOT NULL,
    vaccination_id  BIGINT,
    severity        VARCHAR(20) NOT NULL, -- 'MILD', 'MODERATE', 'SEVERE'
    description     TEXT NOT NULL,
    action_taken    TEXT,
    reported_by     BIGINT NOT NULL,
    reported_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_adverse_event_patient FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    CONSTRAINT fk_adverse_event_vaccination FOREIGN KEY (vaccination_id) REFERENCES vaccinations(id) ON DELETE SET NULL,
    CONSTRAINT fk_adverse_event_reporter FOREIGN KEY (reported_by) REFERENCES users(id) ON DELETE RESTRICT
);

-- Add has_severe_adverse_events flag to patients table
ALTER TABLE patients ADD COLUMN IF NOT EXISTS has_severe_adverse_events BOOLEAN NOT NULL DEFAULT false;

-- Create Indexes for adverse_events table
CREATE INDEX IF NOT EXISTS idx_adverse_event_patient ON adverse_events(patient_id);
CREATE INDEX IF NOT EXISTS idx_adverse_event_vaccination ON adverse_events(vaccination_id);
CREATE INDEX IF NOT EXISTS idx_adverse_event_severity ON adverse_events(severity);

-- Create index for patients with severe adverse events
CREATE INDEX IF NOT EXISTS idx_patients_severe_adverse_events ON patients(has_severe_adverse_events);

