-- Create SMS Logs Table
CREATE TABLE IF NOT EXISTS sms_logs
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_phone VARCHAR(20) NOT NULL,
    message         TEXT NOT NULL,
    status          VARCHAR(20) NOT NULL, -- 'SENT', 'FAILED', 'PENDING'
    error_message   TEXT,
    appointment_id  UUID,
    patient_id      UUID,
    sent_at         TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sms_log_appointment FOREIGN KEY (appointment_id) REFERENCES appointments(id) ON DELETE SET NULL,
    CONSTRAINT fk_sms_log_patient FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE SET NULL
);

-- Create Indexes for sms_logs table
CREATE INDEX IF NOT EXISTS idx_sms_log_recipient ON sms_logs(recipient_phone);
CREATE INDEX IF NOT EXISTS idx_sms_log_status ON sms_logs(status);
CREATE INDEX IF NOT EXISTS idx_sms_log_appointment ON sms_logs(appointment_id);
CREATE INDEX IF NOT EXISTS idx_sms_log_patient ON sms_logs(patient_id);
CREATE INDEX IF NOT EXISTS idx_sms_log_sent_at ON sms_logs(sent_at);

