CREATE TABLE patients
(
    id            UUID                        NOT NULL,
    full_name     VARCHAR(255)                NOT NULL,
    date_of_birth date                        NOT NULL,
    gender        VARCHAR(10)                 NOT NULL,
    guardian_name VARCHAR(255),
    phone_number  VARCHAR(20),
    address       TEXT,
    facility_id   VARCHAR(50)                 NOT NULL,
    deleted       BOOLEAN                     NOT NULL,
    deleted_at    TIMESTAMP WITHOUT TIME ZONE,
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by    BIGINT,
    CONSTRAINT pk_patients PRIMARY KEY (id)
);

CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username    VARCHAR(50)                             NOT NULL,
    password    VARCHAR(255)                            NOT NULL,
    role        VARCHAR(50)                             NOT NULL,
    facility_id VARCHAR(50),
    district_id VARCHAR(50),
    national_id VARCHAR(50),
    active      BOOLEAN                                 NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by  BIGINT,
    deleted     BOOLEAN                                 NOT NULL,
    deleted_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE vaccinations
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patient_id        UUID                                    NOT NULL,
    batch_id          BIGINT                                  NOT NULL,
    nurse_id          BIGINT                                  NOT NULL,
    vaccine_name      VARCHAR(100)                            NOT NULL,
    dose_number       INTEGER                                 NOT NULL,
    date_administered date                                    NOT NULL,
    facility_id       VARCHAR(50)                             NOT NULL,
    notes             VARCHAR(500),
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_vaccinations PRIMARY KEY (id)
);

CREATE TABLE vaccine_batches
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    batch_number       VARCHAR(50)                             NOT NULL,
    vaccine_name       VARCHAR(100)                            NOT NULL,
    manufacturer       VARCHAR(100)                            NOT NULL,
    quantity_received  INTEGER                                 NOT NULL,
    quantity_remaining INTEGER                                 NOT NULL,
    expiry_date        date                                    NOT NULL,
    receipt_date       date                                    NOT NULL,
    facility_id        VARCHAR(50)                             NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by         BIGINT,
    CONSTRAINT pk_vaccine_batches PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE vaccine_batches
    ADD CONSTRAINT uk_batch_facility UNIQUE (batch_number, facility_id);

CREATE INDEX idx_batch_vaccinations ON vaccinations (batch_id);

CREATE INDEX idx_expiry_date ON vaccine_batches (expiry_date);

CREATE INDEX idx_facility_batches ON vaccine_batches (facility_id);

CREATE INDEX idx_facility_id ON users (facility_id);

CREATE INDEX idx_facility_patients ON patients (facility_id);

CREATE INDEX idx_facility_vaccinations ON vaccinations (facility_id);

CREATE INDEX idx_patient_deleted ON patients (deleted);

CREATE INDEX idx_patient_dob ON patients (date_of_birth);

CREATE INDEX idx_patient_vaccinations ON vaccinations (patient_id);

CREATE INDEX idx_role ON users (role);

CREATE INDEX idx_username ON users (username);

CREATE INDEX idx_vaccination_date ON vaccinations (date_administered);

CREATE INDEX idx_vaccine_name ON vaccine_batches (vaccine_name);